---
version: "3.7"
services:
  db:
    image: mysql
    ports: ["3306:3306"]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
